services:

  postgres:
    image: postgres:17.4
    container_name: authDB
    environment:
      POSTGRES_DB: authDB
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      PGDATA: /var/lib/postgresql/data
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  postgresQueue:
    image: postgres:17.4
    container_name: queueDB
    environment:
      POSTGRES_DB: queueDB
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      PGDATA: /var/lib/postgresql/data
    volumes:
      - postgresQueue:/var/lib/postgresql/data
    ports:
      - "5433:5432"

volumes:
  postgres:
  postgresQueue: