jwt:
  secret: secretkeyPasswordForAuth12312312312313213123123sdfsdf
  life-time: 1800000

bootstrap:
  admin:
    username: ${BOOTSTRAP_ADMIN_USERNAME:admin}
    password: ${BOOTSTRAP_ADMIN_PASSWORD:}